# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1259c389f2fd1449e0da24fe6953a5a5a2fd137caf6ff176eb3cafff398f247ecf21b78bd38084e77c4a216500c532c8be228e126a54fe296b5a0511a7c632c

test:
  secret_key_base: e643170a5b36724b49effd8e56e0079e2fab0b45915a61e30fd13342aab3fb2ee05addc785ac4cc9e5c994596cc8576ab4f064eb2873940244e24290803e2f21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
